"use strict";
let fname;
fname = "Naani";
let newname = fname.toUpperCase();
console.log(newname);
let age;
age = 28;
let isValid = true;
console.log(isValid);
let listA;
listA = ["A", "B", "C"];
let listNum;
listNum = [1, 2, 3, 4, 5];
let results = listNum.filter((num) => num > 2);
console.log(results);
